import PDFDocument from "pdfkit";
import { ChartJSNodeCanvas } from "chartjs-node-canvas";
import FinancialAnalysis from "../models/FinancialAnalysis.js";
import Statement from "../models/Statements.js";
import Transaction from "../models/Transaction.js";
import User from "../models/User.js";

const width = 800;
const height = 400;
const chartJSNodeCanvas = new ChartJSNodeCanvas({ width, height });

export const downloadReport = async (req, res) => {
  try {
    const { statementId } = req.params;
    const userId = req.userId;
    const user = await User.findById(userId);

    const statement = await Statement.findOne({
      _id: statementId,
      user: userId,
    });

    const analysis = await FinancialAnalysis.findOne({
      statement: statementId,
      user: userId,
    });

    if (!statement || !analysis) {
      return res.status(404).json({
        message: "Report data not found",
      });
    }

    const transactions = await Transaction.find({
      statement: statementId,
      user: userId,
    });

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=MoneyMitra360_Report_${statementId}.pdf`,
    );

    doc.pipe(res);

    /* ================= HEADER ================= */
    doc
      .fontSize(22)
      .fillColor("#1a237e")
      .text("Money Mitra 360", { align: "center" });

    doc
      .fontSize(12)
      .fillColor("gray")
      .text("AI-Powered Financial Intelligence Report", {
        align: "center",
      });

    doc.moveDown(2);

    doc
      .fontSize(14)
      .fillColor("#000")
      .text("Financial Report Prepared For:", { align: "center" });

    doc.fontSize(18).fillColor("#1a237e").text(user.name, { align: "center" });

    doc.moveDown(2);
    /* ================= SUMMARY SECTION ================= */

    doc.fillColor("black").fontSize(14).text("Financial Overview", {
      underline: true,
    });

    doc.moveDown();

    doc.fontSize(12);
    doc.text(`Statement ID: ${statementId}`);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`);
    doc.text(`User: ${user.name} (${user.email})`);
    doc.text(`Total Transactions: ${statement.totalTransactions}`);
    doc.text(`Financial Score: ${analysis.financialScore}`);
    doc.text(`Financial Status: ${analysis.financialStatus}`);
    doc.text(`Savings Rate: ${analysis.savingsRate}%`);
    doc.text(`Risk Level: ${analysis.riskLevel}`);

    doc.moveDown(2);

    /* ================= MONTHLY TREND CHART ================= */

    const monthly = analysis.monthlyAnalytics || [];

    const months = monthly.map((m) => m.month);
    const expenses = monthly.map((m) => m.expense);

    const expenseChart = await chartJSNodeCanvas.renderToBuffer({
      type: "line",
      data: {
        labels: months,
        datasets: [
          {
            label: "Monthly Expense",
            data: expenses,
            borderWidth: 2,
          },
        ],
      },
    });

    doc.addPage();
    doc.fontSize(16).text("Monthly Expense Trend", { align: "center" });
    doc.moveDown();
    doc.image(expenseChart, {
      fit: [500, 300],
      align: "center",
    });

    /* ================= CATEGORY BREAKDOWN ================= */

    const categoryMap = {};

    transactions
      .filter((t) => t.type === "DEBIT")
      .forEach((txn) => {
        if (!categoryMap[txn.category]) {
          categoryMap[txn.category] = 0;
        }
        categoryMap[txn.category] += Math.abs(txn.amount);
      });

    const categories = Object.keys(categoryMap);
    const values = Object.values(categoryMap);

    const categoryChart = await chartJSNodeCanvas.renderToBuffer({
      type: "bar",
      data: {
        labels: categories,
        datasets: [
          {
            label: "Spending by Category",
            data: values,
          },
        ],
      },
    });

    doc.addPage();
    doc.fontSize(16).text("Category Breakdown", { align: "center" });
    doc.moveDown();
    doc.image(categoryChart, {
      fit: [500, 300],
      align: "center",
    });

    /* ================= AI SUMMARY ================= */

    doc.addPage();
    doc.fontSize(16).text("AI Financial Insights", {
      underline: true,
    });

    doc.moveDown();
    doc.fontSize(12).text(analysis.aiSummary || "No AI insights available.");

    doc.moveDown(2);

    /* ================= WATERMARK ================= */

    doc.opacity(0.08);
    doc.fontSize(60);
    doc.text("Money Mitra 360", 100, 300, {
      angle: 45,
    });
    doc.opacity(1);

    /* ================= FOOTER ================= */

    doc.fontSize(10);
    doc.fillColor("gray");
    doc.text(
      "Confidential Financial Report | Generated by Money Mitra 360",
      50,
      doc.page.height - 50,
      { align: "center" },
    );

    doc.end();
  } catch (error) {
    console.error("PDF Error:", error);

    if (!res.headersSent) {
      res.status(500).json({
        message: "Failed to generate report",
        error: error.message,
      });
    }
  }
};
